apiVersion: v1
kind: pod
metadata:
  name: worker-app
  lables:
    name: worker-app
    app: demo-voting-app
spec:
  containers:
    - name: voting-app
      image: kodekloud/examplevotingapp_worker:v1
      ports: 
        - containerPort: 80
    
