apiVersion: v1
kind: pod
metadata:
  name: redis-app
  lables:
    name: redis-app
    app: demo-voting-app
spec:
  containers:
    - name: redis
      image: redis
      ports: 
        - conatainerPort: 6379
    
