apiVersion: v1
kind: pod
metadata:
  name: result-app
  lables:
    name: result-app
    app: demo-voting-app
spec:
  containers:
    - name: result-app
      image: kodekloud/examplevotingapp_result:v1
      ports: 
        - conatainerPort: 80
    
