apiVersion: v1
kind: pod
metadata:
  name: voting-app
  lables:
    name: voting-app
    app: demo-voting-app
spec:
  containers:
    - name: voting-app
      image: kodekloud/examplevotingapp_vote:v1
      ports: 
        - conatainerPort: 80
    
